server:
  port: 8090



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  global-config:
    banner: false
    db-config:
      db-type: mysql
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  type-aliases-package: com.dragon.hei.wsth.mapper.po
  mapper-locations:
    - classpath*:mybatis/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null

logging:
  level:
    com.dragon.hei.wsth: debug